### PR TITLE
dependency updates

### PR DESCRIPTION
**Pull request by gevorgmansuryan**

### CODE REVIEW

**Comment by luke-** [comment]
@gevorgmansuryan Are you planning any more tests here? As soon as it's finished, I can also test it.
Is there a BC in the API?

**Comment by gevorgmansuryan** [comment]
@luke- Yes, currently I'm checking https://github.com/kreait/firebase-php/blob/7.x/UPGRADE-7.0.md, also planging to do more tests

**Comment by gevorgmansuryan** [comment]
@luke- based on UPGRADE-7.0.md in all used classes and methods mainly added non-contravariant php8 types. Checked them all, and all should work fine. No any breaking changes.

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@gevorgmansuryan Thanks! Please also add such changes in the CHANGELOG in future!

**Comment by gevorgmansuryan** [comment]
@luke- just forgot for this one when created draft. Sorry

**Pull request merged**
